Repository ironcore-dev/metal-operator, pull requests merged in 2024-08, with the labels that each got.

#89 Expose BIOS configuration in `Server` type
  api/v1alpha1/server_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bmc/bmc.go
  bmc/redfish.go
  bmc/redfish_local.go
  config/crd/bases/metal.ironcore.dev_servers.yaml
  docs/api-reference/api.md
  internal/controller/server_controller.go
Labels: documentation, enhancement, api-change, size/XL

#102 Make webhook port configurable
  cmd/manager/main.go
Labels: enhancement, size/XS

#105 Add Format Key to Default Ignition Secret
  internal/controller/server_controller.go
Labels: bug, size/XS

#107 Do not always set `BootSourceOverrideMode`
  bmc/redfish.go
Labels: bug, size/S

#109 Allow the discovery of `Servers` which are in the powered `On` state.
  .github/workflows/lint.yml
  Dockerfile
  Makefile
  bmc/redfish_local.go
  cmd/manager/main.go
  internal/controller/bmc_controller_test.go
  internal/controller/endpoint_controller.go
  internal/controller/endpoint_controller_test.go
  internal/controller/server_controller.go
  internal/controller/server_controller_test.go
  internal/controller/serverclaim_controller.go
  internal/controller/serverclaim_controller_test.go
  internal/controller/suite_test.go
  internal/controller/testdata/ignition.go
  internal/probe/probe_suite_test.go
  internal/registry/registry_suite_test.go
Labels: enhancement, size/L

#112 Improve network inteface filtering in `metalprobe`
  internal/probe/networking.go
Labels: enhancement, size/S

#113 Switch default webhook port from `9443` to `9445`
  cmd/manager/main.go
  config/default/manager_webhook_patch.yaml
  config/webhook/service.yaml
Labels: enhancement, size/XS

#114 Add time triggered `Server` polling
  cmd/manager/main.go
  internal/controller/server_controller.go
  internal/controller/suite_test.go
Labels: enhancement, size/L
