Repository ironcore-dev/metal-operator, pull requests merged in 2024-10, with the labels that each got.

#136 Add timeout check in discovery state
  cmd/manager/main.go
  internal/controller/server_controller.go
  internal/controller/server_controller_test.go
  internal/controller/suite_test.go
Labels: enhancement, size/M

#139 Do not double encode Secrets in `BMCSecret`
  internal/controller/bmcutils.go
  internal/controller/endpoint_controller.go
  internal/controller/endpoint_controller_test.go
  internal/controller/server_controller_test.go
  internal/controller/serverclaim_controller_test.go
Labels: bug, size/M

#143 Extract storage details of a `Server` using Redfish
  api/v1alpha1/server_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bmc/bmc.go
  bmc/redfish.go
  config/crd/bases/metal.ironcore.dev_servers.yaml
  docs/api-reference/api.md
  internal/controller/server_controller.go
  internal/controller/server_controller_test.go
Labels: documentation, size/L, api-change

#152 Add initial project documentation
  .github/workflows/publish-docs.yml
  .reuse/dep5
  Makefile
  docs/Dockerfile
  docs/README.md
  docs/api-reference/api.md
  docs/architecture.md
  docs/concepts/bmcs.md
  docs/concepts/bmcsecrets.md
  docs/concepts/endpoints.md
  docs/concepts/serverbootconfigurations.md
  docs/concepts/serverclaims.md
  docs/concepts/servers.md
  docs/development/dev_docs.md
  docs/development/dev_setup.md
  docs/requirements.txt
  hack/api-reference/config.json
  internal/controller/server_controller_test.go
  mkdocs.yml
Labels: documentation, enhancement, size/XL

#153 Switch port of local docs setup to `9000`
  Makefile
  docs/Dockerfile
Labels: size/XS, chore

#151 Add inline `Endpoint` to `BMC` type
  api/v1alpha1/bmc_types.go
  api/v1alpha1/bmc_webhook.go
  api/v1alpha1/bmc_webhook_test.go
  api/v1alpha1/bmcsecret_types.go
  api/v1alpha1/server_types.go
  api/v1alpha1/webhook_suite_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  bmc/bmc.go
  cmd/manager/main.go
  config/crd/bases/metal.ironcore.dev_bmcs.yaml
  config/crd/bases/metal.ironcore.dev_servers.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_bmcs.yaml
  config/crd/patches/webhook_in_bmcs.yaml
  config/network-policy/allow-webhook-traffic.yaml
  config/webhook/manifests.yaml
  docs/api-reference/api.md
  internal/controller/bmc_controller.go
  internal/controller/bmc_controller_test.go
  internal/controller/bmcutils.go
  internal/controller/endpoint_controller.go
  internal/controller/endpoint_controller_test.go
  internal/controller/server_controller_test.go
  internal/controller/serverclaim_controller_test.go
Labels: documentation, enhancement, api-change, size/XL, breaking

#156 Fix default webhook port and disable metrics server in test suite
  api/v1alpha1/webhook_suite_test.go
  internal/controller/suite_test.go
Labels: bug, size/S, api-change

#157 Update API reference docs
  docs/api-reference/api.md
Labels: documentation, size/M, chore

#158 Fix multiple `ServerClaims` claiming same `Server` object
  internal/controller/serverclaim_controller.go
Labels: bug, size/S
