Repository ironcore-dev/metal-operator, pull requests merged in 2024-11, with the labels that each got.

#159 Claim only `PoweredOff` Servers
  internal/controller/server_controller.go
  internal/controller/serverclaim_controller.go
Labels: bug, size/S

#161 Use lower-case `Server` UUIDs
  bmc/redfish.go
  internal/controller/bmc_controller.go
Labels: enhancement, size/XS

#163 Add `drives` and `volumes` to `server.status.storages`
  api/v1alpha1/server_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bmc/bmc.go
  bmc/redfish.go
  config/crd/bases/metal.ironcore.dev_servers.yaml
  docs/api-reference/api.md
  internal/controller/server_controller.go
  internal/controller/server_controller_test.go
Labels: documentation, size/L, api-change, breaking

#166 Log `BMC` address when creating a client for an `Endpoint`
  internal/controller/endpoint_controller.go
Labels: enhancement, size/XS

#172 Fix BMC IPv6 address handling
  internal/controller/bmcutils.go
  internal/controller/endpoint_controller.go
Labels: bug, size/S

#169 Migrate to CRD validation rules
  PROJECT
  api/v1alpha1/bmc_types.go
  api/v1alpha1/bmc_webhook.go
  api/v1alpha1/bmc_webhook_test.go
  api/v1alpha1/serverclaim_types.go
  api/v1alpha1/serverclaim_webhook.go
  api/v1alpha1/serverclaim_webhook_test.go
  api/v1alpha1/webhook_suite_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/manager/main.go
  config/crd/bases/metal.ironcore.dev_bmcs.yaml
  config/crd/bases/metal.ironcore.dev_serverclaims.yaml
  config/default/kustomization.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  internal/controller/bmc_controller_test.go
  internal/controller/serverclaim_controller_test.go
Labels: api-change, size/XXL

#176 Remove certificate resource from kustomization
  config/default/kustomization.yaml
Labels: size/L, chore

#179 Add `add-license` and `check-license` `make` directive
  Makefile
  hack/license-header.txt
Labels: enhancement, size/S

#174 Add wait polling for retrieving redfish storages and systems
  api/v1alpha1/zz_generated.deepcopy.go
  bmc/bmc.go
  bmc/redfish.go
  bmc/redfish_kube.go
  bmc/redfish_local.go
  cmd/manager/main.go
  internal/controller/bmc_controller.go
  internal/controller/bmcutils.go
  internal/controller/endpoint_controller.go
  internal/controller/server_controller.go
  internal/controller/suite_test.go
Labels: size/L, api-change

#182 Remove certificate mount from kustomization
  config/default/kustomization.yaml
Labels: size/XS, chore

#187 Add `Endpoint` webhook ensuring unique MAC addresses
  PROJECT
  cmd/manager/main.go
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  internal/webhook/v1alpha1/endpoint_webhook.go
  internal/webhook/v1alpha1/endpoint_webhook_test.go
  internal/webhook/v1alpha1/webhook_suite_test.go
Labels: enhancement, size/XL
