Repository ironcore-dev/metal-operator, pull requests merged in 2024-09, with the labels that each got.

#123 Change resource naming scheme
  api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/bmc_controller_test.go
  internal/controller/bmcutils.go
  internal/controller/endpoint_controller.go
  internal/controller/endpoint_controller_test.go
  internal/controller/server_controller_test.go
Labels: enhancement, size/M, breaking

#125 Add handling of `Reset` ad-hoc operation to `Server` type
  bmc/bmc.go
  bmc/redfish.go
  internal/controller/server_controller.go
Labels: enhancement, size/M

#120 Add `Tilt` for local development
  .golangci.yml
  Makefile
  Tiltfile
  api/v1alpha1/bmc_types.go
  bmc/redfish_kube.go
  config/dev/kustomization.yaml
  config/dev/macdb.yaml
  config/dev/manager_patch.yaml
  config/dev/registry_service.yaml
  config/rbac/role.yaml
  config/redfish-mockup/kustomization.yaml
  config/redfish-mockup/redfish_mockup_endpoint.yaml
  config/redfish-mockup/redfish_mockup_service.yaml
  docs/dev_setup.md
  internal/controller/bmcutils.go
  internal/controller/endpoint_controller.go
  internal/controller/server_controller.go
  scripts/kind-with-registry.sh
Labels: documentation, enhancement, api-change, size/XL

#126 Bump golang to 1.23
  .github/workflows/lint.yml
  Makefile
  go.mod
Labels: size/XS, chore

#128 Wait for `Server` power transition
  api/v1alpha1/webhook_suite_test.go
  cmd/manager/main.go
  internal/controller/server_controller.go
  internal/controller/suite_test.go
  internal/probe/agent_test.go
Labels: enhancement, api-change, size/M

#130 Set `MaxConcurrentReconciles` for ServerClaim controller
  internal/controller/serverclaim_controller.go
Labels: bug, size/XS

#129 Retry with `ForcePowerOff` if graceful shutdown times out
  Dockerfile
  bmc/bmc.go
  bmc/redfish.go
  cmd/manager/main.go
  internal/controller/server_controller.go
Labels: enhancement, size/M

#133 Ensure port 8080 is free when running `make test`
  .github/workflows/test.yml
Labels: size/S, chore

#132 Add `Server` model to `.status`
  api/v1alpha1/bmc_types.go
  api/v1alpha1/server_types.go
  config/crd/bases/metal.ironcore.dev_bmcs.yaml
  config/crd/bases/metal.ironcore.dev_servers.yaml
  internal/controller/server_controller.go
  internal/controller/server_controller_test.go
Labels: enhancement, size/S, api-change
