Repository ironcore-dev/metal-operator, pull requests merged in 2024-07, with the labels that each got.

#51 Move project to `ironcore-dev`
  PROJECT
  README.md
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/manager/main.go
  cmd/metalprobe/main.go
  go.mod
  internal/controller/bmc_controller.go
  internal/controller/bmc_controller_test.go
  internal/controller/bmcsecret_controller.go
  internal/controller/bmcsecret_controller_test.go
  internal/controller/bmcutils.go
  internal/controller/endpoint_controller.go
  internal/controller/endpoint_controller_test.go
  internal/controller/helper.go
  internal/controller/server_controller.go
  internal/controller/server_controller_test.go
  internal/controller/serverbootconfiguration_controller.go
  internal/controller/serverbootconfiguration_controller_test.go
  internal/controller/serverclaim_controller.go
  internal/controller/serverclaim_controller_test.go
  internal/controller/suite_test.go
  internal/probe/agent.go
  internal/probe/agent_test.go
  internal/probe/networking.go
  internal/probe/probe_suite_test.go
  internal/registry/registry_suite_test.go
  internal/registry/server.go
  internal/registry/server_test.go
  test/e2e/e2e_test.go
Labels: documentation, api-change, size/M, chore

#52 Update project tooling
  .github/workflows/lint.yml
  Makefile
  test/e2e/e2e_suite_test.go
  test/utils/utils.go
Labels: size/S, chore

#53 Rename operator image to `metal-operator-controller-manager`
  .github/workflows/publish-docker.yml
Labels: size/XS, chore

#54 Make project REUSE API compliant
  .github/workflows/reuse.yml
  .reuse/dep5
  api/v1alpha1/bmc_types.go
  api/v1alpha1/bmcsecret_types.go
  api/v1alpha1/common_types.go
  api/v1alpha1/constants.go
  api/v1alpha1/endpoint_types.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/server_types.go
  api/v1alpha1/serverbootconfiguration_types.go
  api/v1alpha1/serverclaim_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bmc/bmc.go
  bmc/redfish.go
  bmc/redfish_local.go
  cmd/manager/main.go
  cmd/metalprobe/main.go
  hack/boilerplate.go.txt
  internal/api/macdb/macdb.go
  internal/api/registry/registry.go
  internal/api/registry/server.go
  internal/controller/bmc_controller.go
  internal/controller/bmc_controller_test.go
  internal/controller/bmcsecret_controller.go
  internal/controller/bmcsecret_controller_test.go
  internal/controller/bmcutils.go
  internal/controller/endpoint_controller.go
  internal/controller/endpoint_controller_test.go
  internal/controller/helper.go
  internal/controller/server_controller.go
  internal/controller/server_controller_test.go
  internal/controller/serverbootconfiguration_controller.go
  internal/controller/serverbootconfiguration_controller_test.go
  internal/controller/serverclaim_controller.go
  internal/controller/serverclaim_controller_test.go
  internal/controller/suite_test.go
  internal/controller/testdata/ignition.go
  internal/ignition/default.go
  internal/probe/agent.go
  internal/probe/agent_test.go
  internal/probe/networking.go
  internal/probe/probe_suite_test.go
  internal/registry/registry_suite_test.go
  internal/registry/server.go
  internal/registry/server_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
  test/utils/utils.go
Labels: chore, size/XL

#70 Allow deletion of the `ServerClaim` when `Server` does not exist
  internal/controller/serverclaim_controller.go
  internal/controller/serverclaim_controller_test.go
Labels: bug, size/M

#69 Bump `k8s.io/*` to v0.30.2
  Makefile
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/metal.ironcore.dev_bmcs.yaml
  config/crd/bases/metal.ironcore.dev_bmcsecrets.yaml
  config/crd/bases/metal.ironcore.dev_endpoints.yaml
  config/crd/bases/metal.ironcore.dev_serverbootconfigurations.yaml
  config/crd/bases/metal.ironcore.dev_serverclaims.yaml
  config/crd/bases/metal.ironcore.dev_servers.yaml
  go.mod
  go.sum
Labels: size/L, api-change, chore

#72 Add local dev setup guide
  docs/dev_setup.md
Labels: documentation, size/M

#74 Add API reference docs generation
  .github/workflows/check-codegen.yml
  Makefile
  api/v1alpha1/doc.go
  api/v1alpha1/zz_generated.deepcopy.go
  docs/api-reference/api.md
  hack/api-reference/config.json
  hack/api-reference/template/members.tpl
  hack/api-reference/template/pkg.tpl
  hack/api-reference/template/type.tpl
Labels: documentation, enhancement, api-change, size/XXL

#75 Add documentation to API types
  api/v1alpha1/bmc_types.go
  api/v1alpha1/server_types.go
  api/v1alpha1/serverbootconfiguration_types.go
  api/v1alpha1/serverclaim_types.go
  docs/api-reference/api.md
Labels: documentation, size/L, api-change, chore

#84 Add support for inline BMC access in `Server` reconciler
  api/v1alpha1/bmc_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/metal.ironcore.dev_bmcs.yaml
  config/crd/bases/metal.ironcore.dev_serverbootconfigurations.yaml
  config/crd/bases/metal.ironcore.dev_serverclaims.yaml
  config/crd/bases/metal.ironcore.dev_servers.yaml
  internal/controller/bmc_controller.go
  internal/controller/bmcutils.go
  internal/controller/endpoint_controller.go
  internal/controller/endpoint_controller_test.go
  internal/controller/server_controller.go
  internal/controller/server_controller_test.go
  internal/controller/suite_test.go
Labels: enhancement, size/L, api-change

#88 Add validating webhook for `ServerClaim`
  PROJECT
  api/v1alpha1/serverclaim_webhook.go
  api/v1alpha1/serverclaim_webhook_test.go
  api/v1alpha1/webhook_suite_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/manager/main.go
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_serverclaims.yaml
  config/crd/patches/webhook_in_serverclaims.yaml
  config/default/kustomization.yaml
  config/default/manager_webhook_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
Labels: enhancement, api-change, size/XL, ok-to-image

#86 Implement `ServerSelector` in `ServerClaimReconciler`
  api/v1alpha1/serverclaim_types.go
  internal/controller/serverclaim_controller.go
  internal/controller/serverclaim_controller_test.go
Labels: documentation, enhancement, size/L, api-change

#94 Enable `cert-manager` config in kustomization
  config/default/kustomization.yaml
  config/default/webhookcainjection_patch.yaml
Labels: bug, size/L

#95 Add `config/dev` kustomize
  config/dev/delete_manager_auth_proxy_patch.yaml
  config/dev/kustomization.yaml
Labels: enhancement, size/S

#96 Add sample manifests
  config/samples/metal_v1alpha1_bmc.yaml
  config/samples/metal_v1alpha1_bmcsecret.yaml
  config/samples/metal_v1alpha1_server.yaml
  config/samples/metal_v1alpha1_serverbootconfiguration.yaml
  config/samples/metal_v1alpha1_serverclaim.yaml
Labels: enhancement, size/M
