Repository ironcore-dev/metal-operator, pull requests merged in 2024-12, with the labels that each got.

#190 Fix multiple `ServerClaim` references
  internal/controller/serverclaim_controller.go
Labels: bug, size/M

#192 Fix sporadic test failures
  internal/controller/bmc_controller_test.go
  internal/controller/server_controller.go
  internal/controller/server_controller_test.go
  internal/controller/suite_test.go
Labels: bug, size/M

#193 Fix sporadic in probe tests
  .github/workflows/test.yml
  internal/probe/agent_test.go
  internal/probe/probe_suite_test.go
  internal/registry/registry_suite_test.go
Labels: bug, size/M

#162 Add `metalctl` command line interface
  cmd/metalctl/app/app.go
  cmd/metalctl/app/move.go
  cmd/metalctl/main.go
  cmdutils/clients.go
  cmdutils/move.go
  cmdutils/move_test.go
  cmdutils/suite_test.go
  cmdutils/utils.go
  docs/usage/metalctl.md
  go.mod
  go.sum
Labels: documentation, enhancement, api-change, size/XL

#195 Add systemUUID to Server CRD
  api/v1alpha1/server_types.go
  config/crd/bases/metal.ironcore.dev_servers.yaml
  docs/api-reference/api.md
  internal/controller/bmc_controller.go
  internal/controller/bmc_controller_test.go
  internal/controller/server_controller.go
  internal/controller/server_controller_test.go
  internal/controller/serverclaim_controller_test.go
Labels: documentation, enhancement, size/L, api-change, breaking

#198 Add metalctl usage to mkdocs
  mkdocs.yml
Labels: documentation, size/XS

#199 Restructure `metalctl` documentation
  docs/usage/metalctl.md
  mkdocs.yml
Labels: documentation, size/S, chore

#200 Add installation instructions for `metalctl`
  docs/usage/metalctl.md
Labels: documentation, size/S, chore

#197 Fix webhook cert injection
  config/default/kustomization.yaml
Labels: bug, size/L

#202 Fix webhook port in service to 9445
  config/webhook/service.yaml
Labels: bug, size/XS

#201 Add `metalctl console` subcommand
  cmd/metalctl/app/app.go
  cmd/metalctl/app/console.go
  docs/architecture.md
  docs/usage/metalctl.md
  go.mod
  go.sum
  internal/bmcutils/bmcutils.go
  internal/console/console.go
  internal/console/console_test.go
  internal/console/suite_test.go
  internal/controller/bmc_controller.go
  internal/controller/bmc_controller_test.go
  internal/controller/endpoint_controller.go
  internal/controller/server_controller.go
Labels: documentation, enhancement, size/XL

#205 Fix dev setup documentation
  docs/development/dev_setup.md
Labels: documentation, size/XS, chore
