Repository ironcore-dev/metal-operator, pull requests merged in 2025-07, with the labels that each got.

#376 Validate that the claim in `Server` is not switched directly
  api/v1alpha1/server_types.go
  config/crd/bases/metal.ironcore.dev_servers.yaml
  dist/chart/templates/crd/metal.ironcore.dev_servers.yaml
Labels: enhancement, api-change, size/XS, area/metal-automation

#386 Add Conditions to`BIOSSettings` status
  api/v1alpha1/biossettings_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/manager/main.go
  config/crd/bases/metal.ironcore.dev_biossettings.yaml
  dist/chart/templates/crd/metal.ironcore.dev_biossettings.yaml
  docs/api-reference/api.md
  internal/controller/biossettings_controller.go
  internal/controller/biossettings_controller_test.go
  internal/controller/suite_test.go
Labels: documentation, enhancement, api-change, size/XL, area/metal-automation

#389 Use optimisitc lock when claiming a Server
  internal/controller/serverclaim_controller.go
Labels: enhancement, size/XS

#388 Harmonize API comments and marker
  api/v1alpha1/biossettings_types.go
  api/v1alpha1/biosversion_types.go
  api/v1alpha1/bmc_types.go
  api/v1alpha1/bmcsettings_types.go
  api/v1alpha1/endpoint_types.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/server_types.go
  api/v1alpha1/serverbootconfiguration_types.go
  api/v1alpha1/serverclaim_types.go
  api/v1alpha1/servermaintenance_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/metal.ironcore.dev_biossettings.yaml
  config/crd/bases/metal.ironcore.dev_biosversions.yaml
  config/crd/bases/metal.ironcore.dev_bmcs.yaml
  config/crd/bases/metal.ironcore.dev_bmcsettings.yaml
  config/crd/bases/metal.ironcore.dev_endpoints.yaml
  config/crd/bases/metal.ironcore.dev_servermaintenances.yaml
  dist/chart/templates/crd/metal.ironcore.dev_biossettings.yaml
  dist/chart/templates/crd/metal.ironcore.dev_biosversions.yaml
  dist/chart/templates/crd/metal.ironcore.dev_bmcs.yaml
  dist/chart/templates/crd/metal.ironcore.dev_bmcsettings.yaml
  dist/chart/templates/crd/metal.ironcore.dev_endpoints.yaml
  dist/chart/templates/crd/metal.ironcore.dev_servermaintenances.yaml
  docs/api-reference/api.md
  internal/controller/biosversion_controller.go
  internal/controller/biosversion_controller_test.go
Labels: documentation, enhancement, api-change, chore, size/XL, area/metal-automation

#391 Remove claim mutex from `ServerClaim` reconciler
  internal/controller/serverclaim_controller.go
Labels: enhancement, size/M, area/metal-automation

#387 Add `Server` validation webhook
  PROJECT
  cmd/manager/main.go
  config/webhook/manifests.yaml
  dist/chart/templates/webhook/webhooks.yaml
  internal/controller/biossettings_controller.go
  internal/controller/biosversion_controller.go
  internal/controller/bmcsettings_controller.go
  internal/controller/bmcversion_controller.go
  internal/controller/server_controller.go
  internal/controller/suite_test.go
  internal/webhook/v1alpha1/biossettings_webhook.go
  internal/webhook/v1alpha1/biossettings_webhook_test.go
  internal/webhook/v1alpha1/biosversion_webhook.go
  internal/webhook/v1alpha1/biosversion_webhook_test.go
  internal/webhook/v1alpha1/bmcsettings_webhook.go
  internal/webhook/v1alpha1/bmcsettings_webhook_test.go
  internal/webhook/v1alpha1/bmcversion_webhook.go
  internal/webhook/v1alpha1/helper.go
  internal/webhook/v1alpha1/server_webhook.go
  internal/webhook/v1alpha1/server_webhook_test.go
  internal/webhook/v1alpha1/webhook_suite_test.go
Labels: enhancement, api-change, size/XL, area/metal-automation

#401 Harmonize lint and test workflows
  .github/workflows/lint.yml
  .github/workflows/test.yml
  Makefile
Labels: size/M, chore

#410 Use `GeneratedNames` when creating `ServerMaintenance` for `BIOSSettings`
  internal/controller/biosversionset_controller_test.go
  internal/controller/bmcsettings_controller.go
  internal/controller/bmcsettings_controller_test.go
  internal/controller/bmcversion_controller.go
  internal/controller/bmcversion_controller_test.go
Labels: enhancement, size/M, area/metal-automation
