Repository ironcore-dev/metal-operator, pull requests merged in 2025-04, with the labels that each got.

#278 Fix `Server` state transitions (maintenance->reseverd->available)
  internal/controller/server_controller.go
Labels: bug, size/S

#279 Fix typo in `SSHKeyPairSecretPasswordKeyName`
  internal/controller/server_controller.go
  internal/controller/server_controller_test.go
Labels: size/S, chore

#280 Bump golang to 1.24 and `k8s.io/*` deps to v0.32.3
  .github/workflows/publish-docker.yml
  go.mod
  go.sum
Labels: enhancement, size/M

#261 Add per `BMC` protocol scheme configuration in macdb
  api/v1alpha1/bmc_types.go
  config/crd/bases/metal.ironcore.dev_bmcs.yaml
  config/crd/bases/metal.ironcore.dev_servers.yaml
  docs/api-reference/api.md
  docs/concepts/bmcs.md
  internal/api/macdb/macdb.go
  internal/bmcutils/bmcutils.go
  internal/controller/endpoint_controller.go
  internal/controller/helper.go
Labels: documentation, enhancement, size/L

#243 Drop `kube-rbac-proxy` container usage in `config`
  .github/workflows/test-chart.yml
  .github/workflows/test-e2e.yml
  Dockerfile
  Makefile
  cmd/manager/main.go
  config/certmanager/certificate-metrics.yaml
  config/certmanager/certificate-webhook.yaml
  config/certmanager/certificate.yaml
  config/certmanager/issuer.yaml
  config/certmanager/kustomization.yaml
  config/crd/kustomization.yaml
  config/default/cert_metrics_manager_patch.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/default/manager_metrics_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/default/metrics_service.yaml
  config/e2e-metrics-validation/kustomization.yaml
  config/e2e-metrics-validation/manager_args_patch.yaml
  config/manager/manager.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/prometheus/monitor_tls_patch.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/kustomization.yaml
  config/rbac/metrics_auth_role.yaml
  config/rbac/metrics_auth_role_binding.yaml
  config/rbac/metrics_reader_role.yaml
  config/webhook/service.yaml
  dist/chart/templates/crd/metal.ironcore.dev_bmcs.yaml
  dist/chart/templates/crd/metal.ironcore.dev_servers.yaml
  dist/chart/templates/manager/manager.yaml
  dist/chart/templates/rbac/auth_proxy_service.yaml
  dist/chart/templates/rbac/metrics_auth_role.yaml
  dist/chart/templates/rbac/metrics_auth_role_binding.yaml
  dist/chart/templates/rbac/metrics_reader_role.yaml
  dist/chart/values.yaml
  go.mod
  go.sum
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
  test/utils/utils.go
Labels: enhancement, api-change, size/XL

#301 Skip `ServerClaim` reconciliation when `Server` is in `Maintenance` state
  internal/controller/serverclaim_controller.go
Labels: size/S

#294 Add documentation for `BIOSSettings` resource
  docs/architecture.md
  docs/concepts/biossettings.md
  mkdocs.yml
Labels: documentation, enhancement, size/M

#317 Update Helm release workflow
  .github/workflows/publish-chart.yml
Labels: enhancement, size/M

#318 Disable e2e tests on main pushes
  .github/workflows/test-e2e.yml
Labels: size/XS, chore
