Repository ironcore-dev/metal-operator, pull requests merged in 2025-02, with the labels that each got.

#230 Fix `ServerClaim` with label selector claiming multiple servers
  internal/controller/serverclaim_controller.go
  internal/controller/serverclaim_controller_test.go
Labels: bug, size/L

#231 Order resource deletions in controller tests properly
  internal/controller/bmc_controller_test.go
  internal/controller/bmcsecret_controller_test.go
  internal/controller/endpoint_controller_test.go
  internal/controller/server_controller_test.go
  internal/controller/serverbootconfiguration_controller_test.go
  internal/controller/serverclaim_controller_test.go
  internal/controller/suite_test.go
Labels: enhancement, size/L

#235 Add `instance-type` annotation constant
  api/v1alpha1/constants.go
Labels: enhancement, api-change, size/XS

#236 Validate Server discovery failure in an extra test
  internal/controller/server_controller_test.go
Labels: enhancement, size/M

#246 Set the correct `ServerReconciler` max reconciles
  cmd/manager/main.go
  internal/controller/server_controller.go
Labels: bug, size/S

#249 Update reuse configuration
  REUSE.toml
Labels: size/S, chore
