Repository ironcore-dev/metal-operator, pull requests merged in 2025-05, with the labels that each got.

#324 Prepare CRDs folder with kustomize
  .github/workflows/publish-chart.yml
Labels: enhancement, size/S, area/metal-automation

#328 Improve resource cleanup in suite tests
  internal/controller/suite_test.go
Labels: bug, size/M

#298 Check for pending tasks during `BIOSSettings` update
  api/v1alpha1/biossettings_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bmc/bmc.go
  bmc/redfish.go
  bmc/redfish_local.go
  cmd/manager/main.go
  config/crd/bases/metal.ironcore.dev_biossettings.yaml
  config/samples/metal_v1alpha1_biossettings.yaml
  dist/chart/templates/crd/metal.ironcore.dev_biossettings.yaml
  docs/api-reference/api.md
  internal/controller/biossettings_controller.go
  internal/controller/biossettings_controller_test.go
  internal/webhook/v1alpha1/biossettings_webhook_test.go
Labels: documentation, api-change, size/XL, breaking, area/metal-automation

#321 Update docs for BIOS/BMC settings and version types
  docs/README.md
  docs/architecture.md
  docs/concepts/biossettings.md
  docs/concepts/biosversion.md
  docs/concepts/bmcsettings.md
  docs/concepts/bmcversion.md
  mkdocs.yml
Labels: documentation, size/L, area/metal-automation

#329 Add processor information to `Server` status
  api/v1alpha1/server_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bmc/bmc.go
  bmc/redfish.go
  config/crd/bases/metal.ironcore.dev_servers.yaml
  dist/chart/templates/crd/metal.ironcore.dev_servers.yaml
  docs/api-reference/api.md
  internal/controller/server_controller.go
  internal/controller/server_controller_test.go
Labels: documentation, enhancement, size/L, api-change

#335 Use 9443 port for webhook
  cmd/manager/main.go
  config/webhook/service.yaml
  dist/chart/templates/_helpers.tpl
  dist/chart/templates/manager/manager.yaml
Labels: enhancement, size/L

#311 Add `BIOSVersion` resource and controller implementation
  PROJECT
  api/v1alpha1/biossettings_types.go
  api/v1alpha1/biosversion_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bmc/bmc.go
  bmc/mockup.go
  bmc/oem/dell.go
  bmc/oem/hpe.go
  bmc/oem/lenovo.go
  bmc/oem/types.go
  bmc/redfish.go
  bmc/redfish_local.go
  cmd/manager/main.go
  config/crd/bases/metal.ironcore.dev_biossettings.yaml
  config/crd/bases/metal.ironcore.dev_biosversions.yaml
  config/crd/kustomization.yaml
  config/rbac/biosversion_admin_role.yaml
  config/rbac/biosversion_editor_role.yaml
  config/rbac/biosversion_viewer_role.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  config/samples/kustomization.yaml
  config/samples/metal_v1alpha1_biosversion.yaml
  config/webhook/manifests.yaml
  dist/chart/templates/crd/metal.ironcore.dev_biossettings.yaml
  dist/chart/templates/crd/metal.ironcore.dev_biosversions.yaml
  dist/chart/templates/rbac/biosversion_admin_role.yaml
  dist/chart/templates/rbac/biosversion_editor_role.yaml
  dist/chart/templates/rbac/biosversion_viewer_role.yaml
  dist/chart/templates/rbac/role.yaml
  dist/chart/templates/webhook/webhooks.yaml
  docs/api-reference/api.md
  docs/concepts/biosversion.md
  internal/controller/biossettings_controller.go
  internal/controller/biossettings_controller_test.go
  internal/controller/biosversion_controller.go
  internal/controller/biosversion_controller_test.go
  internal/controller/suite_test.go
  internal/webhook/v1alpha1/biosversion_webhook.go
  internal/webhook/v1alpha1/biosversion_webhook_test.go
  internal/webhook/v1alpha1/webhook_suite_test.go
Labels: documentation, enhancement, api-change, size/XXL, area/metal-automation
