Repository ironcore-dev/metal-operator, pull requests merged in 2025-03, with the labels that each got.

#251 Parallelize `ServerClaim` reconciliation
  cmd/manager/main.go
  internal/controller/serverclaim_controller.go
  internal/controller/serverclaim_controller_test.go
  internal/controller/suite_test.go
Labels: enhancement, size/L

#248 Add `is-default-os-image` annotation to discovery boot SBC
  internal/controller/server_controller.go
  internal/controller/server_controller_test.go
Labels: enhancement, size/M

#260 Enhance `BMCReconciler` for Improved Robustness and Efficiency
  api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/bmc_controller.go
Labels: enhancement, api-change, size/M

#264 Add helm charts
  .github/workflows/check-codegen.yml
  .github/workflows/test-chart.yml
  Makefile
  PROJECT
  REUSE.toml
  dist/chart/.helmignore
  dist/chart/Chart.yaml
  dist/chart/templates/_helpers.tpl
  dist/chart/templates/certmanager/certificate.yaml
  dist/chart/templates/crd/metal.ironcore.dev_bmcs.yaml
  dist/chart/templates/crd/metal.ironcore.dev_bmcsecrets.yaml
  dist/chart/templates/crd/metal.ironcore.dev_endpoints.yaml
  dist/chart/templates/crd/metal.ironcore.dev_serverbootconfigurations.yaml
  dist/chart/templates/crd/metal.ironcore.dev_serverclaims.yaml
  dist/chart/templates/crd/metal.ironcore.dev_servermaintenances.yaml
  dist/chart/templates/crd/metal.ironcore.dev_servers.yaml
  dist/chart/templates/manager/manager.yaml
  dist/chart/templates/metrics/metrics-service.yaml
  dist/chart/templates/network-policy/allow-webhook-traffic.yaml
  dist/chart/templates/prometheus/monitor.yaml
  dist/chart/templates/rbac/auth_proxy_client_clusterrole.yaml
  dist/chart/templates/rbac/auth_proxy_role.yaml
  dist/chart/templates/rbac/auth_proxy_role_binding.yaml
  dist/chart/templates/rbac/auth_proxy_service.yaml
  dist/chart/templates/rbac/bmc_editor_role.yaml
  dist/chart/templates/rbac/bmc_viewer_role.yaml
  dist/chart/templates/rbac/bmcsecret_editor_role.yaml
  dist/chart/templates/rbac/bmcsecret_viewer_role.yaml
  dist/chart/templates/rbac/endpoint_editor_role.yaml
  dist/chart/templates/rbac/endpoint_viewer_role.yaml
  dist/chart/templates/rbac/leader_election_role.yaml
  dist/chart/templates/rbac/leader_election_role_binding.yaml
  dist/chart/templates/rbac/role.yaml
  dist/chart/templates/rbac/role_binding.yaml
  dist/chart/templates/rbac/server_editor_role.yaml
  dist/chart/templates/rbac/server_viewer_role.yaml
  dist/chart/templates/rbac/serverbootconfiguration_editor_role.yaml
  dist/chart/templates/rbac/serverbootconfiguration_viewer_role.yaml
  dist/chart/templates/rbac/serverclaim_editor_role.yaml
  dist/chart/templates/rbac/serverclaim_viewer_role.yaml
  dist/chart/templates/rbac/service_account.yaml
  dist/chart/templates/webhook/service.yaml
  dist/chart/templates/webhook/webhooks.yaml
  dist/chart/values.yaml
  docs/usage/installation.md
  go.mod
  go.sum
Labels: documentation, enhancement, size/XXL

#273 Use upstream docs publishing workflow
  .github/workflows/publish-docs.yml
Labels: enhancement, size/M

#265 Add `MaintenanceReconciler` implementation
  PROJECT
  api/v1alpha1/server_types.go
  api/v1alpha1/servermaintenance_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/manager/main.go
  config/crd/bases/metal.ironcore.dev_servers.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  config/rbac/servermaintenance_admin_role.yaml
  config/rbac/servermaintenance_editor_role.yaml
  config/rbac/servermaintenance_viewer_role.yaml
  config/samples/kustomization.yaml
  config/samples/metal_v1alpha1_servermaintenance.yaml
  internal/controller/server_controller.go
  internal/controller/servermaintenance_controller.go
  internal/controller/servermaintenance_controller_test.go
  internal/controller/suite_test.go
Labels: enhancement, api-change, size/XXL

#275 Update API reference docs
  .github/workflows/check-codegen.yml
  api/v1alpha1/zz_generated.deepcopy.go
  dist/chart/templates/crd/metal.ironcore.dev_servers.yaml
  dist/chart/templates/rbac/role.yaml
  dist/chart/templates/rbac/servermaintenance_admin_role.yaml
  dist/chart/templates/rbac/servermaintenance_editor_role.yaml
  dist/chart/templates/rbac/servermaintenance_viewer_role.yaml
  docs/api-reference/api.md
  hack/api-reference/config.json
Labels: documentation, size/L, api-change, chore
