Repository ironcore-dev/metal-operator, pull requests merged in 2025-06, with the labels that each got.

#352 Rename `BMCOptions` to `Options`
  bmc/redfish.go
  bmc/redfish_kube.go
  bmc/redfish_local.go
  cmd/manager/main.go
  internal/bmcutils/bmcutils.go
  internal/controller/biossettings_controller.go
  internal/controller/biosversion_controller.go
  internal/controller/bmc_controller.go
  internal/controller/endpoint_controller.go
  internal/controller/server_controller.go
  internal/controller/suite_test.go
Labels: enhancement, size/M

#341 Bump `k8s.io/*` to v1.33 and `controller-runtime` to v0.21.0
  Makefile
  cmdutils/suite_test.go
  config/crd/bases/metal.ironcore.dev_biossettings.yaml
  config/crd/bases/metal.ironcore.dev_bmcs.yaml
  config/crd/bases/metal.ironcore.dev_bmcsecrets.yaml
  config/crd/bases/metal.ironcore.dev_endpoints.yaml
  config/crd/bases/metal.ironcore.dev_serverbootconfigurations.yaml
  config/crd/bases/metal.ironcore.dev_serverclaims.yaml
  config/crd/bases/metal.ironcore.dev_servermaintenances.yaml
  config/crd/bases/metal.ironcore.dev_servers.yaml
  dist/chart/templates/crd/metal.ironcore.dev_biossettings.yaml
  dist/chart/templates/crd/metal.ironcore.dev_bmcs.yaml
  dist/chart/templates/crd/metal.ironcore.dev_bmcsecrets.yaml
  dist/chart/templates/crd/metal.ironcore.dev_endpoints.yaml
  dist/chart/templates/crd/metal.ironcore.dev_serverbootconfigurations.yaml
  dist/chart/templates/crd/metal.ironcore.dev_serverclaims.yaml
  dist/chart/templates/crd/metal.ironcore.dev_servermaintenances.yaml
  dist/chart/templates/crd/metal.ironcore.dev_servers.yaml
  docs/api-reference/api.md
  go.mod
  go.sum
  hack/api-reference/config.json
  internal/console/suite_test.go
  internal/controller/suite_test.go
  internal/webhook/v1alpha1/webhook_suite_test.go
Labels: documentation, enhancement, size/L

#363 Fix docs base path
  docs/.vitepress/config.mts
Labels: bug, size/XS

#364 Fix local docs setup
  Makefile
  docs/Dockerfile
  docs/index.md
  hack/start-docs.sh
Labels: bug, documentation, size/M

#355 Adopt Helm charts for remote cluster use case
  .github/workflows/publish-chart.yml
  dist/chart/templates/manager/manager.yaml
  dist/chart/values.yaml
Labels: enhancement, size/S, ok-to-charts

#375 Revert Option for naming `Servers` as the `BMC` objects and related
  cmd/manager/main.go
  internal/controller/bmc_controller.go
Labels: enhancement, size/M

#370 Transition unclaimed `Servers` from `Maintenance` to `Initial` state
  docs/concepts/servers.md
  internal/controller/server_controller.go
  internal/controller/server_controller_test.go
Labels: documentation, enhancement, size/L

#381 Update licensing info in readme and docs
  README.md
  docs/.vitepress/config.mts
Labels: documentation, size/M, chore
